name: catkeys
description: "A new Flutter project."
publish_to: 'none' 

version: 0.0.1+001

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.11.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  flutter_lints: ^2.0.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.1.1
  window_manager: ^0.3.4
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  awesome_snackbar_content: ^0.1.3
  loading_indicator: ^3.1.1
  http: ^1.1.0
  zxing_lib: ^1.1.2
  toastification: ^1.2.1
  flutter_statusbarcolor_ns: ^0.5.0
  audioplayers: ^5.2.1
  flutter_local_notifications: ^17.0.0
  package_info_plus: ^5.0.1
  flutter_markdown: ^0.7.3
  device_info_plus: ^9.1.2
  haptic_feedback: ^0.5.1+1
  mimi:
    git:
      url: https://github.com/LeadRDRK/mimi.git
      ref: main

dependency_overrides:
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf